name: CI

on:
  push:
    branches:
    - production

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: .\build.ps1
      shell: powershell